version: "2"
linters:
  enable:
    - gocognit
    - gocyclo
    - gosec
    - misspell
    - revive
    - unconvert
  disable:
    - errcheck
    - govet
    - staticcheck
    - unused
  settings:
    gocognit:
      min-complexity: 15
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - gocognit
          - gocyclo
          - gosec
        path: _test\.go
      - path: (.+)\.go$
        text: should have a package comment
    paths:
      - (^|/)testdata($|/)
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/Nerzal/gocloak
  exclusions:
    generated: lax
    paths:
      - (^|/)testdata($|/)
