services:
  keycloak:
    build: .
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: secret
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8080:8080"
      - "9000:9000"
    healthcheck:
      test: curl --fail --silent http://localhost:9000/health/ready 2>&1 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - ./testdata/gocloak-realm.json:/opt/keycloak/data/import/gocloak-realm.json:ro
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm"]

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 172.17.0.1:25:1025 # smtp server
      - 172.17.0.1:8025:8025 # web ui
